query GetInfos {
  infos {
    title
    value
  }
}

query GetLogo {
  asset(where: { id: "ckztukhg825wa0b81prkv1aow" }) {
    id
    url
  }
}

mutation UpdateTest($number: Int, $id: ID) {
  updateTest(
    data: { number: $number }
    where: { id: $id }
  ) {
    id
    number
  }
  publishTest(where: { id: $id }, to: PUBLISHED) {
    id
    stage
  }
}

query Tests {
  tests(first: 10) {
    id
    number
    stage
  }
}

query Slides {
  slides {
    slide {
      id
      url
    }
  }
}
