query GetProducts($first: Int!, $after: String) {
  products(first: $first, after: $after) {
    pageInfo {
      hasPreviousPage
      hasNextPage
    }
    edges {
      node {
        title
        id
        priceRange {
          maxVariantPrice {
            amount
          }
        }
        featuredImage {
          url
        }
      }
    }
  }
}

query FindProduct($id: ID, $first: Int) {
  product(id: $id) {
    id
    title
    featuredImage {
      url
    }
    description
    priceRange {
      maxVariantPrice {
        amount
      }
    }
    variants(first: $first) {
      edges {
        node {
          id
          selectedOptions {
            name
            value
          }
        }
      }
    }
  }
}

query FindCursor($first: Int) {
  products(first: $first) {
    edges {
      cursor
    }
  }
}

query GetShopInfo {
  shop {
    description
  }
}

# query FindCart(
#   $id_cart: ID!
#   $first: Int
#   $id_product: ID!
# ) {
#   cart(id: $id_cart) {
#     id
#     lines(first: $first) {
#       edges {
#         node {
#           quantity
#           estimatedCost {
#             totalAmount {
#               amount
#               currencyCode
#             }
#           }
#         }
#       }
#     }
#   }
#   product(id: $id_product) {
#     id
#     title
#   }
# }

mutation CartCreate {
  cartCreate {
    cart {
      id
    }
  }
}

mutation CartLinesAdd(
  $lines: [CartLineInput!]!
  $cartId: ID!
  $first: Int
) {
  cartLinesAdd(lines: $lines, cartId: $cartId) {
    cart {
      id
      estimatedCost {
        totalAmount {
          amount
        }
      }
      lines(first: $first) {
        edges {
          node {
            quantity
          }
        }
      }
    }
  }
}
